version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=localhost
      - KC_PROXY=edge
      - KC_HTTP_ENABLED=true
    command: [ "start-dev" ]
    ports:
      - "8180:8080"
    volumes:
      - ./keycloak-data:/opt/keycloak/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/ready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  store-module:
    build:
      context: ./store-module
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - PAYMENT_MODULE_URL=http://payment-module:8081
      - KEYCLOAK_URL=http://keycloak:8080
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/master
    depends_on:
      - redis
      - payment-module
      - keycloak
    networks:
      - app-network

  payment-module:
    build:
      context: ./payment-module
      dockerfile: dockerfile
    ports:
      - "8081:8081"
    environment:
      - KEYCLOAK_URL=http://keycloak:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge