version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  store-module:
    build:
      context: ./store-module
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - PAYMENT_SERVICE_URL=http://payment-module:8081
    depends_on:
      - redis
      - payment-module
    networks:
      - app-network

  payment-module:
    build:
      context: ./payment-module
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge